name: Run Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install

          LATEST=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
          google-chrome --version

      - name: Build app without tests
        run: ./mvnw clean package -DskipTests

      - name: Start Spring Boot app in background
        run: nohup java -jar target/*.jar &

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Spring Boot is up!"
              break
            fi
            echo "Waiting for Spring Boot app..."
            sleep 5
          done

      - name: Run Selenium Test
        run: ./mvnw test -Dtest=ProductSeleniumTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Publish JUnit results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Selenium UI Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
